"use client";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import Header from "@/component/Header";
import Footer from "@/component/Footer";
import { ParallaxProvider } from "react-scroll-parallax";
import { ContextProvider } from "@/utils/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
        {/* Add favicon */}
        <link rel="icon" href="/images/favicon.ico" style={{width:100, height:"100px"}} />
        <title>PV Classes</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ContextProvider>
          <ParallaxProvider>
            <Header />
            {children}
            <Footer />
          </ParallaxProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
